name: Remote Echidna

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run remote-echidna'
        default: ''
        required: false

jobs:
  remote-echidna:
    name: Run remote-echidna
    uses: aviggiano/remote-echidna/.github/workflows/remote-echidna.yml@main
    with:
      project: "yield-contracts"
      project_git_url: "https://github.com/${{github.repository}}.git"
      project_git_checkout: ${{ inputs.branch }}
      run_tests_cmd: "echidna-test test/invariants/STETHVaultInvariants.sol --contract STETHVaultInvariants --config test/invariants/config-assertion.yaml --test-limit 1000000 || true"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REMOTE_ECHIDNA_S3_BUCKET: ${{ secrets.REMOTE_ECHIDNA_S3_BUCKET }}
      REMOTE_ECHIDNA_EC2_INSTANCE_KEY_NAME: ${{ secrets.REMOTE_ECHIDNA_EC2_INSTANCE_KEY_NAME }}

